# Generated by Django 5.0.3 on 2024-03-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesiteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Легко'), ('2', 'Средне'), ('3', 'Сложно'), ('4', 'Эксперт'), ('5', 'Ивлев')], default='1', max_length=8),
        ),
    ]
